SET @logo="C:\Users\José\Desktop\Laboratório\basedados\JavaEats.jpg";

SET @foto_cli="C:\Users\José\Desktop\Laboratório\basedados\foto_cli.jpg";

SET @pizza_media ="C:\Users\José\Desktop\Laboratório\basedados\Pizza_media.png";	

-- Inserir na tabela concelho
insert into concelho (conc_id, conc_nome) values(106,"Castelo de Paiva");
insert into concelho (conc_id, conc_nome) values(107,"Espinho");
insert into concelho (conc_id, conc_nome) values(108,"Estarreja");
insert into concelho (conc_id, conc_nome) values(109,"Santa Maria da Feira");
insert into concelho (conc_id, conc_nome) values(110,"Ílhavo");
insert into concelho (conc_id, conc_nome) values(111,"Mealhada");
insert into concelho (conc_id, conc_nome) values(112,"Murtosa");
insert into concelho (conc_id, conc_nome) values(113,"Oliveira de Azeméis");
insert into concelho (conc_id, conc_nome) values(114,"Oliveira do Bairro");
insert into concelho (conc_id, conc_nome) values(115,"Ovar");
insert into concelho (conc_id, conc_nome) values(116,"São João da Madeira");
insert into concelho (conc_id, conc_nome) values(117,"Sever do Vouga");
insert into concelho (conc_id, conc_nome) values(118,"Vagos");
insert into concelho (conc_id, conc_nome) values(119,"Vale de Cambra");
insert into concelho (conc_id, conc_nome) values(101,"Águeda");
insert into concelho (conc_id, conc_nome) values(102,"Albergaria-a-Velha");
insert into concelho (conc_id, conc_nome) values(103,"Anadia");
insert into concelho (conc_id, conc_nome) values(104,"Arouca");
insert into concelho (conc_id, conc_nome) values(105,"Aveiro");
insert into concelho (conc_id, conc_nome) values(206,"Castro Verde");
insert into concelho (conc_id, conc_nome) values(207,"Cuba");
insert into concelho (conc_id, conc_nome) values(208,"Ferreira do Alentejo");
insert into concelho (conc_id, conc_nome) values(209,"Mértola");
insert into concelho (conc_id, conc_nome) values(210,"Moura");
insert into concelho (conc_id, conc_nome) values(211,"Odemira");
insert into concelho (conc_id, conc_nome) values(212,"Ourique");
insert into concelho (conc_id, conc_nome) values(213,"Serpa");
insert into concelho (conc_id, conc_nome) values(214,"Vidigueira");
insert into concelho (conc_id, conc_nome) values(201,"Aljustrel");
insert into concelho (conc_id, conc_nome) values(202,"Almodôvar");
insert into concelho (conc_id, conc_nome) values(203,"Alvito");
insert into concelho (conc_id, conc_nome) values(204,"Barrancos");
insert into concelho (conc_id, conc_nome) values(205,"Beja");
insert into concelho (conc_id, conc_nome) values(306,"Esposende");
insert into concelho (conc_id, conc_nome) values(307,"Fafe");
insert into concelho (conc_id, conc_nome) values(308,"Guimarães");
insert into concelho (conc_id, conc_nome) values(309,"Póvoa de Lanhoso");
insert into concelho (conc_id, conc_nome) values(310,"Terras de Bouro");
insert into concelho (conc_id, conc_nome) values(311,"Vieira do Minho");
insert into concelho (conc_id, conc_nome) values(312,"Vila Nova de Famalicão");
insert into concelho (conc_id, conc_nome) values(313,"Vila Verde");
insert into concelho (conc_id, conc_nome) values(314,"Vizela");
insert into concelho (conc_id, conc_nome) values(301,"Amares");
insert into concelho (conc_id, conc_nome) values(302,"Barcelos");
insert into concelho (conc_id, conc_nome) values(303,"Braga");
insert into concelho (conc_id, conc_nome) values(304,"Cabeceiras de Basto");
insert into concelho (conc_id, conc_nome) values(305,"Celorico de Basto");
insert into concelho (conc_id, conc_nome) values(406,"Miranda do Douro");
insert into concelho (conc_id, conc_nome) values(407,"Mirandela");
insert into concelho (conc_id, conc_nome) values(408,"Mogadouro");
insert into concelho (conc_id, conc_nome) values(409,"Torre de Moncorvo");
insert into concelho (conc_id, conc_nome) values(410,"Vila Flor");
insert into concelho (conc_id, conc_nome) values(411,"Vimioso");
insert into concelho (conc_id, conc_nome) values(412,"Vinhais");
insert into concelho (conc_id, conc_nome) values(401,"Alfândega da Fé");
insert into concelho (conc_id, conc_nome) values(402,"Bragança");
insert into concelho (conc_id, conc_nome) values(403,"Carrazeda de Ansiães");
insert into concelho (conc_id, conc_nome) values(404,"Freixo de Espada à  Cinta");
insert into concelho (conc_id, conc_nome) values(405,"Macedo de Cavaleiros");
insert into concelho (conc_id, conc_nome) values(506,"Oleiros");
insert into concelho (conc_id, conc_nome) values(507,"Penamacor");
insert into concelho (conc_id, conc_nome) values(508,"Proença-a-Nova");
insert into concelho (conc_id, conc_nome) values(509,"Sertã");
insert into concelho (conc_id, conc_nome) values(510,"Vila de Rei");
insert into concelho (conc_id, conc_nome) values(511,"Vila Velha de Ródão");
insert into concelho (conc_id, conc_nome) values(501,"Belmonte");
insert into concelho (conc_id, conc_nome) values(502,"Castelo Branco");
insert into concelho (conc_id, conc_nome) values(503,"Covilhã");
insert into concelho (conc_id, conc_nome) values(504,"Fundão");
insert into concelho (conc_id, conc_nome) values(505,"Idanha-a-Nova");
insert into concelho (conc_id, conc_nome) values(606,"Góis");
insert into concelho (conc_id, conc_nome) values(607,"Lousã");
insert into concelho (conc_id, conc_nome) values(608,"Mira");
insert into concelho (conc_id, conc_nome) values(609,"Miranda do Corvo");
insert into concelho (conc_id, conc_nome) values(610,"Montemor-o-Velho");
insert into concelho (conc_id, conc_nome) values(611,"Oliveira do Hospital");
insert into concelho (conc_id, conc_nome) values(612,"Pampilhosa da Serra");
insert into concelho (conc_id, conc_nome) values(613,"Penacova");
insert into concelho (conc_id, conc_nome) values(614,"Penela");
insert into concelho (conc_id, conc_nome) values(615,"Soure");
insert into concelho (conc_id, conc_nome) values(616,"Tábua");
insert into concelho (conc_id, conc_nome) values(617,"Vila Nova de Poiares");
insert into concelho (conc_id, conc_nome) values(601,"Arganil");
insert into concelho (conc_id, conc_nome) values(602,"Cantanhede");
insert into concelho (conc_id, conc_nome) values(603,"Coimbra");
insert into concelho (conc_id, conc_nome) values(604,"Condeixa-a-Nova");
insert into concelho (conc_id, conc_nome) values(605,"Figueira da Foz");
insert into concelho (conc_id, conc_nome) values(706,"Montemor-o-Novo");
insert into concelho (conc_id, conc_nome) values(707,"Mora");
insert into concelho (conc_id, conc_nome) values(708,"Mourão");
insert into concelho (conc_id, conc_nome) values(709,"Portel");
insert into concelho (conc_id, conc_nome) values(710,"Redondo");
insert into concelho (conc_id, conc_nome) values(711,"Reguengos de Monsaraz");
insert into concelho (conc_id, conc_nome) values(712,"Vendas Novas");
insert into concelho (conc_id, conc_nome) values(713,"Viana do Alentejo");
insert into concelho (conc_id, conc_nome) values(714,"Vila Viçosa");
insert into concelho (conc_id, conc_nome) values(701,"Alandroal");
insert into concelho (conc_id, conc_nome) values(702,"Arraiolos");
insert into concelho (conc_id, conc_nome) values(703,"Borba");
insert into concelho (conc_id, conc_nome) values(704,"Estremoz");
insert into concelho (conc_id, conc_nome) values(705,"Évora");
insert into concelho (conc_id, conc_nome) values(806,"Lagoa (Algarve)");
insert into concelho (conc_id, conc_nome) values(807,"Lagos");
insert into concelho (conc_id, conc_nome) values(808,"Loulé");
insert into concelho (conc_id, conc_nome) values(809,"Monchique");
insert into concelho (conc_id, conc_nome) values(810,"Olhão");
insert into concelho (conc_id, conc_nome) values(811,"Portimão");
insert into concelho (conc_id, conc_nome) values(812,"São Brás de Alportel");
insert into concelho (conc_id, conc_nome) values(813,"Silves");
insert into concelho (conc_id, conc_nome) values(814,"Tavira");
insert into concelho (conc_id, conc_nome) values(815,"Vila do Bispo");
insert into concelho (conc_id, conc_nome) values(816,"Vila Real de Santo António");
insert into concelho (conc_id, conc_nome) values(801,"Albufeira");
insert into concelho (conc_id, conc_nome) values(802,"Alcoutim");
insert into concelho (conc_id, conc_nome) values(803,"Aljezur");
insert into concelho (conc_id, conc_nome) values(804,"Castro Marim");
insert into concelho (conc_id, conc_nome) values(805,"Faro");
insert into concelho (conc_id, conc_nome) values(906,"Gouveia");
insert into concelho (conc_id, conc_nome) values(907,"Guarda");
insert into concelho (conc_id, conc_nome) values(908,"Manteigas");
insert into concelho (conc_id, conc_nome) values(909,"Meda");
insert into concelho (conc_id, conc_nome) values(910,"Pinhel");
insert into concelho (conc_id, conc_nome) values(911,"Sabugal");
insert into concelho (conc_id, conc_nome) values(912,"Seia");
insert into concelho (conc_id, conc_nome) values(913,"Trancoso");
insert into concelho (conc_id, conc_nome) values(914,"Vila Nova de Foz Côa");
insert into concelho (conc_id, conc_nome) values(901,"Aguiar da Beira");
insert into concelho (conc_id, conc_nome) values(902,"Almeida");
insert into concelho (conc_id, conc_nome) values(903,"Celorico da Beira");
insert into concelho (conc_id, conc_nome) values(904,"Figueira de Castelo Rodrigo");
insert into concelho (conc_id, conc_nome) values(905,"Fornos de Algodres");
insert into concelho (conc_id, conc_nome) values(1006,"Caldas da Rainha");
insert into concelho (conc_id, conc_nome) values(1007,"Castanheira de Pêra");
insert into concelho (conc_id, conc_nome) values(1008,"Figueiró dos Vinhos");
insert into concelho (conc_id, conc_nome) values(1009,"Leiria");
insert into concelho (conc_id, conc_nome) values(1010,"Marinha Grande");
insert into concelho (conc_id, conc_nome) values(1011,"Nazaré");
insert into concelho (conc_id, conc_nome) values(1012,"Óbidos");
insert into concelho (conc_id, conc_nome) values(1013,"Pedrógão Grande");
insert into concelho (conc_id, conc_nome) values(1014,"Peniche");
insert into concelho (conc_id, conc_nome) values(1015,"Pombal");
insert into concelho (conc_id, conc_nome) values(1016,"Porto de Mós");
insert into concelho (conc_id, conc_nome) values(1001,"Alcobaça");
insert into concelho (conc_id, conc_nome) values(1002,"Alvaiázere");
insert into concelho (conc_id, conc_nome) values(1003,"Ansião");
insert into concelho (conc_id, conc_nome) values(1004,"Batalha");
insert into concelho (conc_id, conc_nome) values(1005,"Bombarral");
insert into concelho (conc_id, conc_nome) values(1106,"Lisboa");
insert into concelho (conc_id, conc_nome) values(1107,"Loures");
insert into concelho (conc_id, conc_nome) values(1108,"Lourinhã");
insert into concelho (conc_id, conc_nome) values(1109,"Mafra");
insert into concelho (conc_id, conc_nome) values(1110,"Oeiras");
insert into concelho (conc_id, conc_nome) values(1111,"Sintra");
insert into concelho (conc_id, conc_nome) values(1112,"Sobral de Monte Agraço");
insert into concelho (conc_id, conc_nome) values(1113,"Torres Vedras");
insert into concelho (conc_id, conc_nome) values(1114,"Vila Franca de Xira");
insert into concelho (conc_id, conc_nome) values(1115,"Amadora");
insert into concelho (conc_id, conc_nome) values(1116,"Odivelas");
insert into concelho (conc_id, conc_nome) values(1101,"Alenquer");
insert into concelho (conc_id, conc_nome) values(1102,"Arruda dos Vinhos");
insert into concelho (conc_id, conc_nome) values(1103,"Azambuja");
insert into concelho (conc_id, conc_nome) values(1104,"Cadaval");
insert into concelho (conc_id, conc_nome) values(1105,"Cascais");
insert into concelho (conc_id, conc_nome) values(1206,"Crato");
insert into concelho (conc_id, conc_nome) values(1207,"Elvas");
insert into concelho (conc_id, conc_nome) values(1208,"Fronteira");
insert into concelho (conc_id, conc_nome) values(1209,"Gavião");
insert into concelho (conc_id, conc_nome) values(1210,"Marvão");
insert into concelho (conc_id, conc_nome) values(1211,"Monforte");
insert into concelho (conc_id, conc_nome) values(1212,"Nisa");
insert into concelho (conc_id, conc_nome) values(1213,"Ponte de Sor");
insert into concelho (conc_id, conc_nome) values(1214,"Portalegre");
insert into concelho (conc_id, conc_nome) values(1215,"Sousel");
insert into concelho (conc_id, conc_nome) values(1201,"Alter do Chão");
insert into concelho (conc_id, conc_nome) values(1202,"Arronches");
insert into concelho (conc_id, conc_nome) values(1203,"Avis");
insert into concelho (conc_id, conc_nome) values(1204,"Campo Maior");
insert into concelho (conc_id, conc_nome) values(1205,"Castelo de Vide");
insert into concelho (conc_id, conc_nome) values(1306,"Maia");
insert into concelho (conc_id, conc_nome) values(1307,"Marco de Canaveses");
insert into concelho (conc_id, conc_nome) values(1308,"Matosinhos");
insert into concelho (conc_id, conc_nome) values(1309,"Paços de Ferreira");
insert into concelho (conc_id, conc_nome) values(1310,"Paredes");
insert into concelho (conc_id, conc_nome) values(1311,"Penafiel");
insert into concelho (conc_id, conc_nome) values(1312,"Porto");
insert into concelho (conc_id, conc_nome) values(1313,"Póvoa de Varzim");
insert into concelho (conc_id, conc_nome) values(1314,"Santo Tirso");
insert into concelho (conc_id, conc_nome) values(1315,"Valongo");
insert into concelho (conc_id, conc_nome) values(1316,"Vila do Conde");
insert into concelho (conc_id, conc_nome) values(1317,"Vila Nova de Gaia");
insert into concelho (conc_id, conc_nome) values(1318,"Trofa");
insert into concelho (conc_id, conc_nome) values(1301,"Amarante");
insert into concelho (conc_id, conc_nome) values(1302,"Baião");
insert into concelho (conc_id, conc_nome) values(1303,"Felgueiras");
insert into concelho (conc_id, conc_nome) values(1304,"Gondomar");
insert into concelho (conc_id, conc_nome) values(1305,"Lousada");
insert into concelho (conc_id, conc_nome) values(1406,"Cartaxo");
insert into concelho (conc_id, conc_nome) values(1407,"Chamusca");
insert into concelho (conc_id, conc_nome) values(1408,"Constância");
insert into concelho (conc_id, conc_nome) values(1409,"Coruche");
insert into concelho (conc_id, conc_nome) values(1410,"Entroncamento");
insert into concelho (conc_id, conc_nome) values(1411,"Ferreira do Zêzere");
insert into concelho (conc_id, conc_nome) values(1412,"Golegã");
insert into concelho (conc_id, conc_nome) values(1413,"Mação");
insert into concelho (conc_id, conc_nome) values(1414,"Rio Maior");
insert into concelho (conc_id, conc_nome) values(1415,"Salvaterra de Magos");
insert into concelho (conc_id, conc_nome) values(1416,"Santarém");
insert into concelho (conc_id, conc_nome) values(1417,"Sardoal");
insert into concelho (conc_id, conc_nome) values(1418,"Tomar");
insert into concelho (conc_id, conc_nome) values(1419,"Torres Novas");
insert into concelho (conc_id, conc_nome) values(1420,"Vila Nova da Barquinha");
insert into concelho (conc_id, conc_nome) values(1421,"Ourém");
insert into concelho (conc_id, conc_nome) values(1401,"Abrantes");
insert into concelho (conc_id, conc_nome) values(1402,"Alcanena");
insert into concelho (conc_id, conc_nome) values(1403,"Almeirim");
insert into concelho (conc_id, conc_nome) values(1404,"Alpiarça");
insert into concelho (conc_id, conc_nome) values(1405,"Benavente");
insert into concelho (conc_id, conc_nome) values(1506,"Moita");
insert into concelho (conc_id, conc_nome) values(1507,"Montijo");
insert into concelho (conc_id, conc_nome) values(1508,"Palmela");
insert into concelho (conc_id, conc_nome) values(1509,"Santiago do Cacém");
insert into concelho (conc_id, conc_nome) values(1510,"Seixal");
insert into concelho (conc_id, conc_nome) values(1511,"Sesimbra");
insert into concelho (conc_id, conc_nome) values(1512,"Setúbal");
insert into concelho (conc_id, conc_nome) values(1513,"Sines");
insert into concelho (conc_id, conc_nome) values(1501,"Alcácer do Sal");
insert into concelho (conc_id, conc_nome) values(1502,"Alcochete");
insert into concelho (conc_id, conc_nome) values(1503,"Almada");
insert into concelho (conc_id, conc_nome) values(1504,"Barreiro");
insert into concelho (conc_id, conc_nome) values(1505,"Grândola");
insert into concelho (conc_id, conc_nome) values(1606,"Ponte da Barca");
insert into concelho (conc_id, conc_nome) values(1607,"Ponte de Lima");
insert into concelho (conc_id, conc_nome) values(1608,"Valença");
insert into concelho (conc_id, conc_nome) values(1609,"Viana do Castelo");
insert into concelho (conc_id, conc_nome) values(1610,"Vila Nova de Cerveira");
insert into concelho (conc_id, conc_nome) values(1601,"Arcos de Valdevez");
insert into concelho (conc_id, conc_nome) values(1602,"Caminha");
insert into concelho (conc_id, conc_nome) values(1603,"Melgaço");
insert into concelho (conc_id, conc_nome) values(1604,"Monção");
insert into concelho (conc_id, conc_nome) values(1605,"Paredes de Coura");
insert into concelho (conc_id, conc_nome) values(1705,"Mondim de Basto");
insert into concelho (conc_id, conc_nome) values(1706,"Montalegre");
insert into concelho (conc_id, conc_nome) values(1707,"Murça");
insert into concelho (conc_id, conc_nome) values(1708,"Peso da Régua");
insert into concelho (conc_id, conc_nome) values(1709,"Ribeira de Pena");
insert into concelho (conc_id, conc_nome) values(1710,"Sabrosa");
insert into concelho (conc_id, conc_nome) values(1711,"Santa Marta de Penaguião");
insert into concelho (conc_id, conc_nome) values(1712,"Valpaços");
insert into concelho (conc_id, conc_nome) values(1713,"Vila Pouca de Aguiar");
insert into concelho (conc_id, conc_nome) values(1714,"Vila Real");
insert into concelho (conc_id, conc_nome) values(1701,"Alijó");
insert into concelho (conc_id, conc_nome) values(1702,"Boticas");
insert into concelho (conc_id, conc_nome) values(1703,"Chaves");
insert into concelho (conc_id, conc_nome) values(1704,"Mesão Frio");
insert into concelho (conc_id, conc_nome) values(1805,"Lamego");
insert into concelho (conc_id, conc_nome) values(1806,"Mangualde");
insert into concelho (conc_id, conc_nome) values(1807,"Moimenta da Beira");
insert into concelho (conc_id, conc_nome) values(1808,"Mortágua");
insert into concelho (conc_id, conc_nome) values(1809,"Nelas");
insert into concelho (conc_id, conc_nome) values(1810,"Oliveira de Frades");
insert into concelho (conc_id, conc_nome) values(1811,"Penalva do Castelo");
insert into concelho (conc_id, conc_nome) values(1812,"Penedono");
insert into concelho (conc_id, conc_nome) values(1813,"Resende");
insert into concelho (conc_id, conc_nome) values(1814,"Santa Comba Dão");
insert into concelho (conc_id, conc_nome) values(1815,"São João da Pesqueira");
insert into concelho (conc_id, conc_nome) values(1816,"São Pedro do Sul");
insert into concelho (conc_id, conc_nome) values(1817,"Sátão");
insert into concelho (conc_id, conc_nome) values(1818,"Sernancelhe");
insert into concelho (conc_id, conc_nome) values(1819,"Tabuaço");
insert into concelho (conc_id, conc_nome) values(1820,"Tarouca");
insert into concelho (conc_id, conc_nome) values(1821,"Tondela");
insert into concelho (conc_id, conc_nome) values(1822,"Vila Nova de Paiva");
insert into concelho (conc_id, conc_nome) values(1823,"Viseu");
insert into concelho (conc_id, conc_nome) values(1824,"Vouzela");
insert into concelho (conc_id, conc_nome) values(1801,"Armamar");
insert into concelho (conc_id, conc_nome) values(1802,"Carregal do Sal");
insert into concelho (conc_id, conc_nome) values(1803,"Castro Daire");
insert into concelho (conc_id, conc_nome) values(1804,"Cinfães");
insert into concelho (conc_id, conc_nome) values(3105,"Ponta do Sol");
insert into concelho (conc_id, conc_nome) values(3106,"Porto Moniz");
insert into concelho (conc_id, conc_nome) values(3107,"Ribeira Brava");
insert into concelho (conc_id, conc_nome) values(3108,"Santa Cruz");
insert into concelho (conc_id, conc_nome) values(3109,"Santana");
insert into concelho (conc_id, conc_nome) values(3110,"São Vicente");
insert into concelho (conc_id, conc_nome) values(3101,"Calheta (Madeira)");
insert into concelho (conc_id, conc_nome) values(3102,"Câmara de Lobos");
insert into concelho (conc_id, conc_nome) values(3103,"Funchal");
insert into concelho (conc_id, conc_nome) values(3104,"Machico");
insert into concelho (conc_id, conc_nome) values(3201,"Porto Santo");
insert into concelho (conc_id, conc_nome) values(4101,"Vila do Porto");
insert into concelho (conc_id, conc_nome) values(4205,"Ribeira Grande");
insert into concelho (conc_id, conc_nome) values(4206,"Vila Franca do Campo");
insert into concelho (conc_id, conc_nome) values(4201,"Lagoa (São Miguel)");
insert into concelho (conc_id, conc_nome) values(4202,"Nordeste");
insert into concelho (conc_id, conc_nome) values(4203,"Ponta Delgada");
insert into concelho (conc_id, conc_nome) values(4204,"Povoação");
insert into concelho (conc_id, conc_nome) values(4301,"Angra do Heroísmo");
insert into concelho (conc_id, conc_nome) values(4302,"Praia da Vitória");
insert into concelho (conc_id, conc_nome) values(4401,"Santa Cruz da Graciosa");
insert into concelho (conc_id, conc_nome) values(4501,"Calheta (São Jorge)");
insert into concelho (conc_id, conc_nome) values(4502,"Velas");
insert into concelho (conc_id, conc_nome) values(4601,"Lajes do Pico");
insert into concelho (conc_id, conc_nome) values(4602,"Madalena");
insert into concelho (conc_id, conc_nome) values(4603,"São Roque do Pico");
insert into concelho (conc_id, conc_nome) values(4701,"Horta");
insert into concelho (conc_id, conc_nome) values(4801,"Lajes das Flores");
insert into concelho (conc_id, conc_nome) values(4802,"Santa Cruz das Flores");
insert into concelho (conc_id, conc_nome) values(4901,"Corvo");

-- Inserir na tabela utilizador
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Filipa Martins","fma1@email.pt","ativo","346908344","953284447","72!GLgZH","Rua do Meio, 50, 2950-555, Palmela",FALSE,"administrador");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Fábio Bravo","fbr2@email.pt","ativo","352240346","954913951","44!SfT_b","Rua do Início, 99, 2830-152 Barreiro",FALSE,"cliente");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Sandra Pereira","spe3@email.pt","ativo","329939894","923878710","15!FGE]r","Avenida da Liberdade, 59, 1120-780, Lisboa",FALSE,"cliente");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("João Messias","jme4@email.pt","ativo","328564326","964775283","54!XXF^k","Rua do Alto, 33, 2900-455, Setúbal",FALSE,"cliente");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("André Pombo","apo5@email.pt","ativo","247694338","953438013","36!Nx]bS","Rua de Cima, 28, 2950-155, Palmela",FALSE,"cliente");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Andreia Plácido","apl6@email.pt","ativo","359076841","923349296","25!VCWUh","Avenida da República, 2B, 1100-034, Lisboa",FALSE,"cliente");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Catarina Cerejo","cce7@email.pt","ativo","335894356","919173299","53!PCW^o","Praça da Virtude, 120-122, 2860-243, Moita",FALSE,"cliente");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Daniel Malhado","dma8@email.pt","ativo","255931074","952925859","92!MpiUK","Rua 25 de Abril, 23A r/c dir 2860-524 Moita",FALSE,"cliente");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Júlio Simões","jsi9@email.pt","ativo","346413527","914609691","20!DA[Tw","Rua do Coreto, 8, 2950-458 Palmela",FALSE,"cliente");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Miguel Machado","mma10@email.pt","ativo","229969578","943566838","32!EPl^x","Rua da Paz dos Anjos, s/n, 2830 Barreiro",FALSE,"cliente");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Paulo Costa","pco11@email.pt","ativo","379046837","966060111","39!TNEBh","Rua de baixo, 340, 2950-575, Palmela",FALSE,"cliente");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Paulo Covas","pco12@email.pt","ativo","285667241","960965566","85!TVZee","Avenida da Liberdade, 111, 1100-241, Lisboa",FALSE,"cliente");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Tiago Landeiroto","tla13@email.pt","ativo","213706474","969570075","15!IY\tz","Praça da Vitória,1, 2860-003, Moita",FALSE,"cliente");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Vítor Nuno","vnu14@email.pt","ativo","202322873","936246615","28!W_xo`","Rua 1º de Maio, 43, 2955-253 Palmela",FALSE,"estafeta");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Wilson Veterano","wve15@email.pt","ativo","219118782","937276101","47!FoWNO","Rua do Futuro,1 8, 2950-008 Palmela",FALSE,"estafeta");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("José Fernandes","jfe16@email.pt","ativo","359475457","959685084","87!B]ZVx","Rua do Fim, 1, 1100-000, Lisboa",FALSE,"estafeta");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("João Cunha","jcu17@email.pt","ativo","345233522","929515724","86!NXsPq","Rua do Futuro,1 8, 2950-008 Palmela",FALSE,"estafeta");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("João Morais","jmo18@email.pt","ativo","322903749","936003012","55!SFOyl","Rua do Passado,32, 2950-014 Palmela",TRUE,"estafeta");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Macdonalds", "macdon@mail.pt", "ativo", "56753677","922222321", "W#FFhty54","Parque das Merenda, 1a, 2830-125, Barreiro",FALSE,  "Estabelecimento");
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("PizzaHut", "pihu@mail.pt", "ativo", "567453691", "958212221", "Q!ERT%4", "Rua Fantasma, 13, 2900-725, Setúbal", FALSE,"Estabelecimento"); 
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("KFC", "kfc@mail.pt", "ativo", "5674523423","92562389", "56Y45654","Centro Comercial do Comércio, 18C, 2830-125, Barreiro",FALSE, "Estabelecimento"); 
insert into utilizador (util_nome, util_email, util_estado, util_nif, util_telemovel, util_password, util_morada, util_bloqueado, util_perfil) values("Burger King", "buki@mail.pt", "ativo", "56746788", "915822214", "%E4345654", "Travessa das Almas, 23, 1000-725, Lisboa", FALSE,"Estabelecimento");

-- Inserir na tabela cliente
insert into cliente ( cli_data_nascimento, cli_cartao_credito, cli_foto_perfil, id_conc, id_util) values (STR_TO_DATE("28/10/1974", "%e/%c/%Y"),"153982046",@foto_cli,1504,2);
insert into cliente ( cli_data_nascimento, cli_cartao_credito, cli_foto_perfil, id_conc, id_util) values (STR_TO_DATE("8/1/1971", "%e/%c/%Y"),"301508130",@foto_cli,1106,3);
insert into cliente ( cli_data_nascimento, cli_cartao_credito, cli_foto_perfil, id_conc, id_util) values (STR_TO_DATE("7/5/1951", "%e/%c/%Y"),"221528190",@foto_cli,1512,4);
insert into cliente ( cli_data_nascimento, cli_cartao_credito, cli_foto_perfil, id_conc, id_util) values (STR_TO_DATE("23/12/1957", "%e/%c/%Y"),"118356912",@foto_cli,1508,5);
insert into cliente ( cli_data_nascimento, cli_cartao_credito, cli_foto_perfil, id_conc, id_util) values (STR_TO_DATE("4/1/1977", "%e/%c/%Y"),"389424002",@foto_cli,1106,6);
insert into cliente ( cli_data_nascimento, cli_cartao_credito, cli_foto_perfil, id_conc, id_util) values (STR_TO_DATE("4/2/1995", "%e/%c/%Y"),"153106271",@foto_cli,1506,7);
insert into cliente ( cli_data_nascimento, cli_cartao_credito, cli_foto_perfil, id_conc, id_util) values (STR_TO_DATE("21/5/1983", "%e/%c/%Y"),"170958235",@foto_cli,1506,8);
insert into cliente ( cli_data_nascimento, cli_cartao_credito, cli_foto_perfil, id_conc, id_util) values (STR_TO_DATE("17/12/1986", "%e/%c/%Y"),"262998975",@foto_cli,1508,9);
insert into cliente ( cli_data_nascimento, cli_cartao_credito, cli_foto_perfil, id_conc, id_util) values (STR_TO_DATE("20/7/1978", "%e/%c/%Y"),"152427881",@foto_cli,1504,10);
insert into cliente ( cli_data_nascimento, cli_cartao_credito, cli_foto_perfil, id_conc, id_util) values (STR_TO_DATE("4/7/1982", "%e/%c/%Y"),"189373943",@foto_cli,1508,11);
insert into cliente ( cli_data_nascimento, cli_cartao_credito, cli_foto_perfil, id_conc, id_util) values (STR_TO_DATE("14/3/1998", "%e/%c/%Y"),"136986328",@foto_cli,1506,12);
insert into cliente ( cli_data_nascimento, cli_cartao_credito, cli_foto_perfil, id_conc, id_util) values (STR_TO_DATE("5/11/1975", "%e/%c/%Y"),"379753946",@foto_cli,1506,13);

-- Inserir na tabela estafeta
insert into estafeta ( estaf_data_nascimento, estaf_categoria_carta, estaf_iban, estaf_disponivel, estaf_niss, estaf_veiculo_motorizado, estaf_foto_perfil,  id_util) values (STR_TO_DATE("5/3/1964", "%e/%c/%Y"),"A","148423307", TRUE, 101660639, TRUE,@foto_cli,14);
insert into estafeta ( estaf_data_nascimento, estaf_categoria_carta, estaf_iban, estaf_disponivel, estaf_niss, estaf_veiculo_motorizado, estaf_foto_perfil,  id_util) values (STR_TO_DATE("16/4/1982", "%e/%c/%Y"),"B","321349304", TRUE, 222057836, TRUE,@foto_cli,15);
insert into estafeta ( estaf_data_nascimento, estaf_categoria_carta, estaf_iban, estaf_disponivel, estaf_niss, estaf_veiculo_motorizado, estaf_foto_perfil,  id_util) values (STR_TO_DATE("11/10/1967", "%e/%c/%Y"),NULL,"115751793", TRUE, 164365331, FALSE,@foto_cli,16);
insert into estafeta ( estaf_data_nascimento, estaf_categoria_carta, estaf_iban, estaf_disponivel, estaf_niss, estaf_veiculo_motorizado, estaf_foto_perfil,  id_util) values (STR_TO_DATE("28/11/1972", "%e/%c/%Y"),"A","171688168", TRUE, 264075421, TRUE,@foto_cli,17);

-- Inserir na tabela estabelecimento
insert into estabelecimento ( estab_iban, estab_tipo_cozinha, estab_logo, estab_horario, id_util) values ("PT35234353534", "Hamburgers",  @logo, "8:00-24:00", 19);
insert into estabelecimento ( estab_iban, estab_tipo_cozinha, estab_logo, estab_horario, id_util) values ("PT25562456224", "Pizas", @logo,"8:00-24:00", 20);
insert into estabelecimento ( estab_iban, estab_tipo_cozinha, estab_logo, estab_horario, id_util) values ("PT2593265584", "Frango", @logo, "8:00-24:00",21);  
insert into estabelecimento ( estab_iban, estab_tipo_cozinha, estab_logo, estab_horario, id_util) values ("PT2587113534", "Hamburgers", @logo, "8:00-24:00", 22); 

-- Inserir na tabela produto
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("cheeseham","Molho de Tomate, Queijo 100% Mozzarella, Orégãos, Fiambre e Mozzarella Extra: Tamanho médio", 14.6,  @pizza_media,TRUE, 1);	
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("serrana","Molho de Tomate, Queijo 100% Mozzarella, Orégãos, Chouriço, Cogumelos Frescos e Azeitonas: Tamanho médio", 14.6, @pizza_media,TRUE, 2);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("veggie lovers","Molho de Tomate, Queijo 100% Mozzarella, Orégãos, Mistura de Vegetais, Milho, Tomate e Azeitonas: Tamanho médio", 14.6, @pizza_media,TRUE, 3);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("summer","Molho de Tomate, Queijo 100% Mozzarella, Orégãos, Chouriço, Ananás e Cebola Crocante: Tamanho médio", 14.6, @pizza_media,TRUE, 4);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("Prosciutto Lovers","Molho de Tomate, 3 Queijos, Presunto, Presunto Extra e Orégãos: Tamanho médio", 14.6, @pizza_media,TRUE, 1);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("bacon lovers","Molho de Tomate, Queijo 100% Mozzarella, Orégãos e Bacon Extra: Tamanho médio", 16.3, @pizza_media,TRUE, 2);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("pepperoni lovers","Molho de Tomate, Queijo 100% Mozzarella, Orégãos e Pepperoni Extra: Tamanho médio", 16.3, @pizza_media,TRUE, 3);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("tropical","Molho de Tomate, Queijo 100% Mozzarella, Orégãos, Ananás, Fiambre e Cogumelos Frescos: Tamanho médio", 16.3, @pizza_media,TRUE, 4);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("portuguesa","Molho de Tomate, Queijo 100% Mozzarella, Orégãos, Chouriço, Mistura de Pimentos: Tamanho médio", 16.3, @pizza_media,TRUE, 1);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("gália","Molho de Tomate, Queijo 100% Mozzarella, Orégãos, Frango, Pepperoni e Ovo Cozido: Tamanho médio", 16.3, @pizza_media,TRUE, 2);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("camponesa","Molho de Tomate, Queijo 100% Mozzarella, Orégãos, Fiambre, Cogumelos Frescos e Tomate: Tamanho médio", 16.3, @pizza_media,TRUE, 3);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("cheese lovers","Molho de Tomate, 3 Queijos, Queijo de Cabra e Orégãos: Tamanho médio", 16.3, @pizza_media,TRUE, 4);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("Prosciutto Garden","Molho de Tomate, Queijo 100% Mozzarella, Presunto, Tomate, Azeitonas e Orégãos.: Tamanho médio", 16.3, @pizza_media,TRUE, 4);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("havaiana","Molho de Tomate, Queijo 100% Mozzarella, Orégãos, Atum, Camarão e Ananás: Tamanho médio", 18, @pizza_media,TRUE, 1);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("garlic & bacon","Molho de Manteiga de Alho, Queijo 100% Mozzarella, Orégãos, Bacon, Cogumelos Frescos e Cebola: Tamanho médio", 18, @pizza_media,TRUE, 2);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("suprema","Molho de Tomate, Queijo 100% Mozzarella, Orégãos, Pepperoni, Carne de Vaca, Mistura de Pimentos,Cogumelos Frescos e Cebola: Tamanho médio", 18, @pizza_media,TRUE, 3);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("barbecue","Molho Barbecue, Queijo 100% Mozzarella, Orégãos, Bacon, Carne de Vaca e Cebola: Tamanho médio", 18, @pizza_media,TRUE, 4);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("farm lovers","Molho Barbecue, Queijo 100% Mozzarella, Orégãos, Frango, Bacon, Milho e Cebola Crocante: Tamanho médio", 18, @pizza_media,TRUE, 1);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("5 queijos ","Molho de Tomate, Queijo Mozzarella, Red Leicester, Monterey Jack, Queijo de Cabra,Parmesão e Orégãos: Tamanho médio", 18, @pizza_media,TRUE, 2);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("super suprema ","Molho de Tomate, Queijo 100% Mozzarella, Orégãos, Pepperoni, Carne de Vaca,Fiambre, Mistura de Pimentos, Cogumelos Frescos, Cebola e Azeitonas: Tamanho médio", 18, @pizza_media,TRUE, 3);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("Prosciutto ","Gourmet Molho de Tomate, Queijo 100% Mozzarela, Presunto, Queijo de Cabra,Cebola Crocante e Orégãos: Tamanho médio", 18, @pizza_media,TRUE, 4);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("BigMac","Com tomate", 3.9, @pizza_media,TRUE, 1);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("CBO","Com queijo", 5.9, @pizza_media,TRUE, 1);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("Batatas pequenas","em pacote", 1.7, @pizza_media,TRUE, 1);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("Batatas médias","feitas na hora", 2.2, @pizza_media,TRUE, 1);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("Batatas grandes","feitas na hora", 2.5, @pizza_media,TRUE, 1);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("Coca-cola pequena","em garrafa", 2.3, @pizza_media,TRUE, 1);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("Coca-cola média","em copo", 2.5, @pizza_media,TRUE, 1);
insert into produto (prod_nome, prod_descricao, prod_preco_atual, prod_foto, prod_estado, id_estab)	values("Coca-cola grande","em copo", 2.6, @pizza_media,TRUE, 1);

-- Inserir na tabela encomenda
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (67.4, STR_TO_DATE("24/2/2021", "%e/%c/%Y") ,"12:29","entregue", STR_TO_DATE("24/2/2021"," %e/%c/%Y") ,"12:49", 1,1);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (17.1, STR_TO_DATE("24/2/2021", "%e/%c/%Y") ,"14:12","entregue", STR_TO_DATE("24/2/2021"," %e/%c/%Y") ,"14:50", 2,8);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (2.5, STR_TO_DATE("24/2/2021", "%e/%c/%Y") ,"17:29","entregue", STR_TO_DATE("24/2/2021"," %e/%c/%Y") ,"17:54", 2,10);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (17.1, STR_TO_DATE("24/2/2021", "%e/%c/%Y") ,"21:45","entregue", STR_TO_DATE("24/2/2021"," %e/%c/%Y") ,"22:03", 2,12);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (52.8, STR_TO_DATE("25/2/2021", "%e/%c/%Y") ,"1:40","entregue", STR_TO_DATE("25/2/2021"," %e/%c/%Y") ,"8:35", 2,3);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (34.8, STR_TO_DATE("25/2/2021", "%e/%c/%Y") ,"9:46","entregue", STR_TO_DATE("25/2/2021"," %e/%c/%Y") ,"10:14", 1,9);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (50.6, STR_TO_DATE("25/2/2021", "%e/%c/%Y") ,"13:58","entregue", STR_TO_DATE("25/2/2021"," %e/%c/%Y") ,"14:35", 2,3);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (30.9, STR_TO_DATE("25/2/2021", "%e/%c/%Y") ,"18:21","entregue", STR_TO_DATE("25/2/2021"," %e/%c/%Y") ,"18:48", 3,2);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (31.7, STR_TO_DATE("25/2/2021", "%e/%c/%Y") ,"18:49","entregue", STR_TO_DATE("25/2/2021"," %e/%c/%Y") ,"19:15", 1,1);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (35.1, STR_TO_DATE("25/2/2021", "%e/%c/%Y") ,"21:34","entregue", STR_TO_DATE("25/2/2021"," %e/%c/%Y") ,"21:48", 2,4);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (2.5, STR_TO_DATE("26/2/2021", "%e/%c/%Y") ,"8:07","entregue", STR_TO_DATE("26/2/2021"," %e/%c/%Y") ,"8:36", 2,7);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (18.5, STR_TO_DATE("26/2/2021", "%e/%c/%Y") ,"11:33","entregue", STR_TO_DATE("26/2/2021"," %e/%c/%Y") ,"12:00", 1,9);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (16.3, STR_TO_DATE("26/2/2021", "%e/%c/%Y") ,"14:37","entregue", STR_TO_DATE("26/2/2021"," %e/%c/%Y") ,"15:15", 1,12);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (52.8, STR_TO_DATE("26/2/2021", "%e/%c/%Y") ,"18:29","entregue", STR_TO_DATE("26/2/2021"," %e/%c/%Y") ,"19:03", 2,7);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (71.1, STR_TO_DATE("26/2/2021", "%e/%c/%Y") ,"22:38","entregue", STR_TO_DATE("26/2/2021"," %e/%c/%Y") ,"22:55", 4,5);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (30.9, STR_TO_DATE("27/2/2021", "%e/%c/%Y") ,"7:05","entregue", STR_TO_DATE("27/2/2021"," %e/%c/%Y") ,"8:17", 2,12);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (32.6, STR_TO_DATE("27/2/2021", "%e/%c/%Y") ,"8:20","entregue", STR_TO_DATE("27/2/2021"," %e/%c/%Y") ,"8:17", 2,6);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (38.5, STR_TO_DATE("27/2/2021", "%e/%c/%Y") ,"9:42","entregue", STR_TO_DATE("27/2/2021"," %e/%c/%Y") ,"9:53", 1,1);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (36.5, STR_TO_DATE("27/2/2021", "%e/%c/%Y") ,"12:54","entregue", STR_TO_DATE("27/2/2021"," %e/%c/%Y") ,"13:30", 1,6);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (5.9, STR_TO_DATE("27/2/2021", "%e/%c/%Y") ,"14:37","entregue", STR_TO_DATE("27/2/2021"," %e/%c/%Y") ,"15:07", 2,3);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (16.3, STR_TO_DATE("27/2/2021", "%e/%c/%Y") ,"18:35","entregue", STR_TO_DATE("27/2/2021"," %e/%c/%Y") ,"19:12", 2,6);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (2.3, STR_TO_DATE("27/2/2021", "%e/%c/%Y") ,"20:28","entregue", STR_TO_DATE("27/2/2021"," %e/%c/%Y") ,"20:53", 2,8);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (21.9, STR_TO_DATE("28/2/2021", "%e/%c/%Y") ,"6:48","entregue", STR_TO_DATE("28/2/2021"," %e/%c/%Y") ,"8:24", 1,9);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (67.7, STR_TO_DATE("28/2/2021", "%e/%c/%Y") ,"11:33","entregue", STR_TO_DATE("28/2/2021"," %e/%c/%Y") ,"11:58", 1,1);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (33.2, STR_TO_DATE("28/2/2021", "%e/%c/%Y") ,"14:29","entregue", STR_TO_DATE("28/2/2021"," %e/%c/%Y") ,"15:08", 2,7);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (31.7, STR_TO_DATE("28/2/2021", "%e/%c/%Y") ,"16:31","entregue", STR_TO_DATE("28/2/2021"," %e/%c/%Y") ,"16:59", 1,3);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (16.9, STR_TO_DATE("28/2/2021", "%e/%c/%Y") ,"19:03","entregue", STR_TO_DATE("28/2/2021"," %e/%c/%Y") ,"19:21", 2,3);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (5.9, STR_TO_DATE("28/2/2021", "%e/%c/%Y") ,"23:06","entregue", STR_TO_DATE("28/2/2021"," %e/%c/%Y") ,"23:37", 1,4);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (21.9, STR_TO_DATE("1/3/2021", "%e/%c/%Y") ,"9:48","entregue", STR_TO_DATE("1/3/2021"," %e/%c/%Y") ,"10:22", 2,6);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (16.3, STR_TO_DATE("1/3/2021", "%e/%c/%Y") ,"9:51","entregue", STR_TO_DATE("1/3/2021"," %e/%c/%Y") ,"10:04", 1,7);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (31.4, STR_TO_DATE("1/3/2021", "%e/%c/%Y") ,"12:03","entregue", STR_TO_DATE("1/3/2021"," %e/%c/%Y") ,"12:40", 1,7);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (17.1, STR_TO_DATE("1/3/2021", "%e/%c/%Y") ,"15:20","entregue", STR_TO_DATE("1/3/2021"," %e/%c/%Y") ,"15:54", 1,9);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (16.3, STR_TO_DATE("1/3/2021", "%e/%c/%Y") ,"19:11","entregue", STR_TO_DATE("1/3/2021"," %e/%c/%Y") ,"19:45", 1,9);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (33.1, STR_TO_DATE("1/3/2021", "%e/%c/%Y") ,"22:02","entregue", STR_TO_DATE("1/3/2021"," %e/%c/%Y") ,"22:28", 1,9);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (2.3, STR_TO_DATE("2/3/2021", "%e/%c/%Y") ,"10:30","entregue", STR_TO_DATE("2/3/2021"," %e/%c/%Y") ,"10:58", 1,12);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (35.1, STR_TO_DATE("2/3/2021", "%e/%c/%Y") ,"13:46","entregue", STR_TO_DATE("2/3/2021"," %e/%c/%Y") ,"14:20", 1,12);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (5.9, STR_TO_DATE("2/3/2021", "%e/%c/%Y") ,"15:44","entregue", STR_TO_DATE("2/3/2021"," %e/%c/%Y") ,"16:17", 1,12);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (20.5, STR_TO_DATE("2/3/2021", "%e/%c/%Y") ,"19:34","entregue", STR_TO_DATE("2/3/2021"," %e/%c/%Y") ,"20:05", 2,12);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (35.1, STR_TO_DATE("2/3/2021", "%e/%c/%Y") ,"23:36","entregue", STR_TO_DATE("2/3/2021"," %e/%c/%Y") ,"23:56", 1,12);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (38.2, STR_TO_DATE("3/3/2021", "%e/%c/%Y") ,"11:45","entregue", STR_TO_DATE("3/3/2021"," %e/%c/%Y") ,"12:17", 1,1);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (53.1, STR_TO_DATE("3/3/2021", "%e/%c/%Y") ,"14:47","entregue", STR_TO_DATE("3/3/2021"," %e/%c/%Y") ,"15:02", 1,2);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (36, STR_TO_DATE("3/3/2021", "%e/%c/%Y") ,"15:39","entregue", STR_TO_DATE("3/3/2021"," %e/%c/%Y") ,"16:00", 4,2);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (48.9, STR_TO_DATE("3/3/2021", "%e/%c/%Y") ,"17:51","entregue", STR_TO_DATE("3/3/2021"," %e/%c/%Y") ,"18:05", 1,3);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (52.8, STR_TO_DATE("3/3/2021", "%e/%c/%Y") ,"20:08","entregue", STR_TO_DATE("3/3/2021"," %e/%c/%Y") ,"20:41", 1,6);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, enc_data_entrega, enc_hora_entrega, id_estaf, id_cli) values (67.5, STR_TO_DATE("3/3/2021", "%e/%c/%Y") ,"22:58","entregue", STR_TO_DATE("3/3/2021"," %e/%c/%Y") ,"23:25", 1,9);
insert into encomenda (enc_preco_total, enc_data_pedido, enc_hora_pedido,  enc_estado_entrega,id_estaf, id_cli) values (67.8, STR_TO_DATE("4/3/2021", "%e/%c/%Y") ,"7:51","atribuido",1,9);
insert into encomenda (enc_preco_total,enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, id_cli) values (69.1, STR_TO_DATE("4/3/2021", "%e/%c/%Y") ,"8:21","aceite",12);
insert into encomenda (enc_preco_total,enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, id_cli) values (48.9, STR_TO_DATE("4/3/2021", "%e/%c/%Y") ,"13:05","aceite",3);
insert into encomenda (enc_preco_total,enc_data_pedido, enc_hora_pedido,  enc_estado_entrega, id_cli) values (66.9, STR_TO_DATE("4/3/2021", "%e/%c/%Y") ,"14:24","pendente",2);

-- Inserir na tabela encomenda_contem_produto
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(1,1,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(1,5,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(1,9,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(1,14,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(1,18,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(1,25,2, 2.20);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(2,1,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(2,9,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(2,28,1, 2.50);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(3,26,2, 2.5);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(4,1,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(4,28,2, 2.5);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(5,4,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(5,8,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(5,17,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(5,22,1, 3.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(6,4,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(6,8,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(6,22,1, 3.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(7,3,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(7,16,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(7,20,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(8,4,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(8,8,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(8,12,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(9,1,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(9,5,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(9,9,2, 16.3);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(9,28,2, 2.5);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(10,1,2, 14.6);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(10,5,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(10,23,2, 5.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(11,26,1, 2.50);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(12,5,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(12,22,1, 3.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(13,5,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(13,24,2, 1.7);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(14,4,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(14,13,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(14,17,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(14,22,1, 3.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(15,4,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(15,8,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(15,12,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(15,13,2, 16.3);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(15,17,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(15,23,1, 5.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(16,4,2, 29.20);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(16,8,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(17,4,2, 14.6);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(17,8,2, 16.3);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(17,12,2, 16.3);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(17,24,1, 1.70);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(18,1,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(18,13,2, 16.3);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(18,17,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(18,18,2, 5.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(18,23,1, 5.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(18,25,1, 2.20);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(19,23,2, 5.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(20,5,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(20,9,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(20,24,1, 1.70);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(21,27,1, 2.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(22,9,2, 16.3);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(22,18,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(22,22,1, 3.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(23,4,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(23,8,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(23,12,2, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(23,13,2, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(23,17,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(23,26,1, 2.50);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(24,4,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(24,8,2, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(24,12,2, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(24,13,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(24,27,1, 2.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(25,1,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(25,5,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(25,28,2, 2.5);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(26,5,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(26,27,2, 2.3);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(27,23,2, 5.9);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(28,14,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(28,18,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(28,22,1, 3.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(29,1,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(29,24,1, 1.70);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(30,1,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(30,5,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(30,14,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(30,25,1, 2.20);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(31,5,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(31,14,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(31,28,2, 2.5);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(32,1,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(32,24,2, 1.7);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(33,1,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(33,5,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(33,14,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(33,22,1, 3.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(34,9,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(34,27,2, 2.3);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(35,1,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(35,18,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(35,26,1, 2.50);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(36,9,2, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(36,14,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(36,23,2, 5.9);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(37,1,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(37,23,1, 5.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(38,5,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(38,14,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(38,23,1, 5.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(39,12,2, 16.3);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(39,13,2, 16.3);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(39,17,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(39,22,1, 3.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(40,4,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(40,8,2, 16.3);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(40,12,2, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(40,13,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(40,23,2, 11.80);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(41,12,2, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(41,13,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(41,17,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(41,24,2, 1.70);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(42,4,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(42,8,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(42,17,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(43,4,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(43,13,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(43,17,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(43,22,1, 3.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(44,4,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(44,8,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(44,12,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(44,13,2, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(44,17,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(44,27,2, 2.3);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(45,13,2, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(45,17,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(45,28,2, 2.50);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(46,4,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(46,8,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(46,12,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(46,13,2, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(46,17,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(46,29,1, 2.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(47,4,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(47,8,2, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(47,12,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(47,13,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(47,17,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(47,22,1, 3.90);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(48,3,2, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(48,7,2, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(48,16,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(48,20,2, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(49,4,1, 14.60);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(49,8,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(49,12,1, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(49,13,2, 16.30);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(49,17,1, 18.0);
insert into encomenda_contem_produto (id_enc, id_prod, enc_prod_quantidade, enc_prod_preco_venda) values(49,24,2, 1.70);

-- Inserir na tabela estabelecimento_serve_concelho
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1506, 1);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1507, 1);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1510, 1);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1511, 1);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1512, 1);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1513, 1);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1502, 1);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1503, 1);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1504, 1);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1505, 1);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1106, 2);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1506, 2);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1507, 2);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1510, 2);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1511, 2);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1512, 2);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1513, 2);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1502, 2);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1503, 2);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1504, 2);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1503, 3);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1510, 3);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1511, 3);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1512, 3);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1106, 4);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1107, 4);
insert into estabelecimento_serve_concelho (id_conc, id_estab) values (1110, 4);

-- Inserir na tabela estafeta_entrega_concelho
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1506,	1);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1507,	1);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1510,	1);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1511,	1);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1512,	1);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1513,	1);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1508,	1);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1509,	1);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1501,	1);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1502,	1);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1106,	2);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1506,	2);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1507,	2);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1510,	2);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1511,	2);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1512,	2);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1513,	2);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1508,	2);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1509,	2);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1501,	2);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1503,	3);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1106,	3);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1107,	3);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1110,	3);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1106,	4);
insert into estafeta_entrega_concelho (id_conc , id_estaf) values(1110,	4);