/*insert into concelho (conc_id, conc_nome) values(106,"Castelo de Paiva");
insert into concelho (conc_id, conc_nome) values(107,"Espinho");
insert into concelho (conc_id, conc_nome) values(108,"Estarreja");
insert into concelho (conc_id, conc_nome) values(109,"Santa Maria da Feira");
insert into concelho (conc_id, conc_nome) values(110,"Ílhavo");
insert into concelho (conc_id, conc_nome) values(111,"Mealhada");
insert into concelho (conc_id, conc_nome) values(112,"Murtosa");
insert into concelho (conc_id, conc_nome) values(113,"Oliveira de Azeméis");
insert into concelho (conc_id, conc_nome) values(114,"Oliveira do Bairro");
insert into concelho (conc_id, conc_nome) values(115,"Ovar");
insert into concelho (conc_id, conc_nome) values(116,"São João da Madeira");
insert into concelho (conc_id, conc_nome) values(117,"Sever do Vouga");
insert into concelho (conc_id, conc_nome) values(118,"Vagos");
insert into concelho (conc_id, conc_nome) values(119,"Vale de Cambra");
insert into concelho (conc_id, conc_nome) values(101,"Águeda");
insert into concelho (conc_id, conc_nome) values(102,"Albergaria-a-Velha");
insert into concelho (conc_id, conc_nome) values(103,"Anadia");
insert into concelho (conc_id, conc_nome) values(104,"Arouca");
insert into concelho (conc_id, conc_nome) values(105,"Aveiro");
insert into concelho (conc_id, conc_nome) values(206,"Castro Verde");
insert into concelho (conc_id, conc_nome) values(207,"Cuba");
insert into concelho (conc_id, conc_nome) values(208,"Ferreira do Alentejo");
insert into concelho (conc_id, conc_nome) values(209,"Mértola");
insert into concelho (conc_id, conc_nome) values(210,"Moura");
insert into concelho (conc_id, conc_nome) values(211,"Odemira");
insert into concelho (conc_id, conc_nome) values(212,"Ourique");
insert into concelho (conc_id, conc_nome) values(213,"Serpa");
insert into concelho (conc_id, conc_nome) values(214,"Vidigueira");
insert into concelho (conc_id, conc_nome) values(201,"Aljustrel");
insert into concelho (conc_id, conc_nome) values(202,"Almodôvar");
insert into concelho (conc_id, conc_nome) values(203,"Alvito");
insert into concelho (conc_id, conc_nome) values(204,"Barrancos");
insert into concelho (conc_id, conc_nome) values(205,"Beja");
insert into concelho (conc_id, conc_nome) values(306,"Esposende");
insert into concelho (conc_id, conc_nome) values(307,"Fafe");
insert into concelho (conc_id, conc_nome) values(308,"Guimarães");
insert into concelho (conc_id, conc_nome) values(309,"Póvoa de Lanhoso");
insert into concelho (conc_id, conc_nome) values(310,"Terras de Bouro");
insert into concelho (conc_id, conc_nome) values(311,"Vieira do Minho");
insert into concelho (conc_id, conc_nome) values(312,"Vila Nova de Famalicão");
insert into concelho (conc_id, conc_nome) values(313,"Vila Verde");
insert into concelho (conc_id, conc_nome) values(314,"Vizela");
insert into concelho (conc_id, conc_nome) values(301,"Amares");
insert into concelho (conc_id, conc_nome) values(302,"Barcelos");
insert into concelho (conc_id, conc_nome) values(303,"Braga");
insert into concelho (conc_id, conc_nome) values(304,"Cabeceiras de Basto");
insert into concelho (conc_id, conc_nome) values(305,"Celorico de Basto");
insert into concelho (conc_id, conc_nome) values(406,"Miranda do Douro");
insert into concelho (conc_id, conc_nome) values(407,"Mirandela");
insert into concelho (conc_id, conc_nome) values(408,"Mogadouro");
insert into concelho (conc_id, conc_nome) values(409,"Torre de Moncorvo");
insert into concelho (conc_id, conc_nome) values(410,"Vila Flor");
insert into concelho (conc_id, conc_nome) values(411,"Vimioso");
insert into concelho (conc_id, conc_nome) values(412,"Vinhais");
insert into concelho (conc_id, conc_nome) values(401,"Alfândega da Fé");
insert into concelho (conc_id, conc_nome) values(402,"Bragança");
insert into concelho (conc_id, conc_nome) values(403,"Carrazeda de Ansiães");
insert into concelho (conc_id, conc_nome) values(404,"Freixo de Espada à  Cinta");
insert into concelho (conc_id, conc_nome) values(405,"Macedo de Cavaleiros");
insert into concelho (conc_id, conc_nome) values(506,"Oleiros");
insert into concelho (conc_id, conc_nome) values(507,"Penamacor");
insert into concelho (conc_id, conc_nome) values(508,"Proença-a-Nova");
insert into concelho (conc_id, conc_nome) values(509,"Sertã");
insert into concelho (conc_id, conc_nome) values(510,"Vila de Rei");
insert into concelho (conc_id, conc_nome) values(511,"Vila Velha de Ródão");
insert into concelho (conc_id, conc_nome) values(501,"Belmonte");
insert into concelho (conc_id, conc_nome) values(502,"Castelo Branco");
insert into concelho (conc_id, conc_nome) values(503,"Covilhã");
insert into concelho (conc_id, conc_nome) values(504,"Fundão");
insert into concelho (conc_id, conc_nome) values(505,"Idanha-a-Nova");
insert into concelho (conc_id, conc_nome) values(606,"Góis");
insert into concelho (conc_id, conc_nome) values(607,"Lousã");
insert into concelho (conc_id, conc_nome) values(608,"Mira");
insert into concelho (conc_id, conc_nome) values(609,"Miranda do Corvo");
insert into concelho (conc_id, conc_nome) values(610,"Montemor-o-Velho");
insert into concelho (conc_id, conc_nome) values(611,"Oliveira do Hospital");
insert into concelho (conc_id, conc_nome) values(612,"Pampilhosa da Serra");
insert into concelho (conc_id, conc_nome) values(613,"Penacova");
insert into concelho (conc_id, conc_nome) values(614,"Penela");
insert into concelho (conc_id, conc_nome) values(615,"Soure");
insert into concelho (conc_id, conc_nome) values(616,"Tábua");
insert into concelho (conc_id, conc_nome) values(617,"Vila Nova de Poiares");
insert into concelho (conc_id, conc_nome) values(601,"Arganil");
insert into concelho (conc_id, conc_nome) values(602,"Cantanhede");
insert into concelho (conc_id, conc_nome) values(603,"Coimbra");
insert into concelho (conc_id, conc_nome) values(604,"Condeixa-a-Nova");
insert into concelho (conc_id, conc_nome) values(605,"Figueira da Foz");
insert into concelho (conc_id, conc_nome) values(706,"Montemor-o-Novo");
insert into concelho (conc_id, conc_nome) values(707,"Mora");
insert into concelho (conc_id, conc_nome) values(708,"Mourão");
insert into concelho (conc_id, conc_nome) values(709,"Portel");
insert into concelho (conc_id, conc_nome) values(710,"Redondo");
insert into concelho (conc_id, conc_nome) values(711,"Reguengos de Monsaraz");
insert into concelho (conc_id, conc_nome) values(712,"Vendas Novas");
insert into concelho (conc_id, conc_nome) values(713,"Viana do Alentejo");
insert into concelho (conc_id, conc_nome) values(714,"Vila Viçosa");
insert into concelho (conc_id, conc_nome) values(701,"Alandroal");
insert into concelho (conc_id, conc_nome) values(702,"Arraiolos");
insert into concelho (conc_id, conc_nome) values(703,"Borba");
insert into concelho (conc_id, conc_nome) values(704,"Estremoz");
insert into concelho (conc_id, conc_nome) values(705,"Évora");
insert into concelho (conc_id, conc_nome) values(806,"Lagoa (Algarve)");
insert into concelho (conc_id, conc_nome) values(807,"Lagos");
insert into concelho (conc_id, conc_nome) values(808,"Loulé");
insert into concelho (conc_id, conc_nome) values(809,"Monchique");
insert into concelho (conc_id, conc_nome) values(810,"Olhão");
insert into concelho (conc_id, conc_nome) values(811,"Portimão");
insert into concelho (conc_id, conc_nome) values(812,"São Brás de Alportel");
insert into concelho (conc_id, conc_nome) values(813,"Silves");
insert into concelho (conc_id, conc_nome) values(814,"Tavira");
insert into concelho (conc_id, conc_nome) values(815,"Vila do Bispo");
insert into concelho (conc_id, conc_nome) values(816,"Vila Real de Santo António");
insert into concelho (conc_id, conc_nome) values(801,"Albufeira");
insert into concelho (conc_id, conc_nome) values(802,"Alcoutim");
insert into concelho (conc_id, conc_nome) values(803,"Aljezur");
insert into concelho (conc_id, conc_nome) values(804,"Castro Marim");
insert into concelho (conc_id, conc_nome) values(805,"Faro");
insert into concelho (conc_id, conc_nome) values(906,"Gouveia");
insert into concelho (conc_id, conc_nome) values(907,"Guarda");
insert into concelho (conc_id, conc_nome) values(908,"Manteigas");
insert into concelho (conc_id, conc_nome) values(909,"Meda");
insert into concelho (conc_id, conc_nome) values(910,"Pinhel");
insert into concelho (conc_id, conc_nome) values(911,"Sabugal");
insert into concelho (conc_id, conc_nome) values(912,"Seia");
insert into concelho (conc_id, conc_nome) values(913,"Trancoso");
insert into concelho (conc_id, conc_nome) values(914,"Vila Nova de Foz Côa");
insert into concelho (conc_id, conc_nome) values(901,"Aguiar da Beira");
insert into concelho (conc_id, conc_nome) values(902,"Almeida");
insert into concelho (conc_id, conc_nome) values(903,"Celorico da Beira");
insert into concelho (conc_id, conc_nome) values(904,"Figueira de Castelo Rodrigo");
insert into concelho (conc_id, conc_nome) values(905,"Fornos de Algodres");
insert into concelho (conc_id, conc_nome) values(1006,"Caldas da Rainha");
insert into concelho (conc_id, conc_nome) values(1007,"Castanheira de Pêra");
insert into concelho (conc_id, conc_nome) values(1008,"Figueiró dos Vinhos");
insert into concelho (conc_id, conc_nome) values(1009,"Leiria");
insert into concelho (conc_id, conc_nome) values(1010,"Marinha Grande");
insert into concelho (conc_id, conc_nome) values(1011,"Nazaré");
insert into concelho (conc_id, conc_nome) values(1012,"Óbidos");
insert into concelho (conc_id, conc_nome) values(1013,"Pedrógão Grande");
insert into concelho (conc_id, conc_nome) values(1014,"Peniche");
insert into concelho (conc_id, conc_nome) values(1015,"Pombal");
insert into concelho (conc_id, conc_nome) values(1016,"Porto de Mós");
insert into concelho (conc_id, conc_nome) values(1001,"Alcobaça");
insert into concelho (conc_id, conc_nome) values(1002,"Alvaiázere");
insert into concelho (conc_id, conc_nome) values(1003,"Ansião");
insert into concelho (conc_id, conc_nome) values(1004,"Batalha");
insert into concelho (conc_id, conc_nome) values(1005,"Bombarral");*/
insert into concelho (conc_id, conc_nome) values(1106,"Lisboa");
insert into concelho (conc_id, conc_nome) values(1107,"Loures");
-- insert into concelho (conc_id, conc_nome) values(1108,"Lourinhã");
-- insert into concelho (conc_id, conc_nome) values(1109,"Mafra");
insert into concelho (conc_id, conc_nome) values(1110,"Oeiras");
/*insert into concelho (conc_id, conc_nome) values(1111,"Sintra");
insert into concelho (conc_id, conc_nome) values(1112,"Sobral de Monte Agraço");
insert into concelho (conc_id, conc_nome) values(1113,"Torres Vedras");
insert into concelho (conc_id, conc_nome) values(1114,"Vila Franca de Xira");
insert into concelho (conc_id, conc_nome) values(1115,"Amadora");
insert into concelho (conc_id, conc_nome) values(1116,"Odivelas");
insert into concelho (conc_id, conc_nome) values(1101,"Alenquer");
insert into concelho (conc_id, conc_nome) values(1102,"Arruda dos Vinhos");
insert into concelho (conc_id, conc_nome) values(1103,"Azambuja");
insert into concelho (conc_id, conc_nome) values(1104,"Cadaval");
insert into concelho (conc_id, conc_nome) values(1105,"Cascais");
insert into concelho (conc_id, conc_nome) values(1206,"Crato");
insert into concelho (conc_id, conc_nome) values(1207,"Elvas");
insert into concelho (conc_id, conc_nome) values(1208,"Fronteira");
insert into concelho (conc_id, conc_nome) values(1209,"Gavião");
insert into concelho (conc_id, conc_nome) values(1210,"Marvão");
insert into concelho (conc_id, conc_nome) values(1211,"Monforte");
insert into concelho (conc_id, conc_nome) values(1212,"Nisa");
insert into concelho (conc_id, conc_nome) values(1213,"Ponte de Sor");
insert into concelho (conc_id, conc_nome) values(1214,"Portalegre");
insert into concelho (conc_id, conc_nome) values(1215,"Sousel");
insert into concelho (conc_id, conc_nome) values(1201,"Alter do Chão");
insert into concelho (conc_id, conc_nome) values(1202,"Arronches");
insert into concelho (conc_id, conc_nome) values(1203,"Avis");
insert into concelho (conc_id, conc_nome) values(1204,"Campo Maior");
insert into concelho (conc_id, conc_nome) values(1205,"Castelo de Vide");
insert into concelho (conc_id, conc_nome) values(1306,"Maia");
insert into concelho (conc_id, conc_nome) values(1307,"Marco de Canaveses");
insert into concelho (conc_id, conc_nome) values(1308,"Matosinhos");
insert into concelho (conc_id, conc_nome) values(1309,"Paços de Ferreira");
insert into concelho (conc_id, conc_nome) values(1310,"Paredes");
insert into concelho (conc_id, conc_nome) values(1311,"Penafiel");
insert into concelho (conc_id, conc_nome) values(1312,"Porto");
insert into concelho (conc_id, conc_nome) values(1313,"Póvoa de Varzim");
insert into concelho (conc_id, conc_nome) values(1314,"Santo Tirso");
insert into concelho (conc_id, conc_nome) values(1315,"Valongo");
insert into concelho (conc_id, conc_nome) values(1316,"Vila do Conde");
insert into concelho (conc_id, conc_nome) values(1317,"Vila Nova de Gaia");
insert into concelho (conc_id, conc_nome) values(1318,"Trofa");
insert into concelho (conc_id, conc_nome) values(1301,"Amarante");
insert into concelho (conc_id, conc_nome) values(1302,"Baião");
insert into concelho (conc_id, conc_nome) values(1303,"Felgueiras");
insert into concelho (conc_id, conc_nome) values(1304,"Gondomar");
insert into concelho (conc_id, conc_nome) values(1305,"Lousada");
insert into concelho (conc_id, conc_nome) values(1406,"Cartaxo");
insert into concelho (conc_id, conc_nome) values(1407,"Chamusca");
insert into concelho (conc_id, conc_nome) values(1408,"Constância");
insert into concelho (conc_id, conc_nome) values(1409,"Coruche");
insert into concelho (conc_id, conc_nome) values(1410,"Entroncamento");
insert into concelho (conc_id, conc_nome) values(1411,"Ferreira do Zêzere");
insert into concelho (conc_id, conc_nome) values(1412,"Golegã");
insert into concelho (conc_id, conc_nome) values(1413,"Mação");
insert into concelho (conc_id, conc_nome) values(1414,"Rio Maior");
insert into concelho (conc_id, conc_nome) values(1415,"Salvaterra de Magos");
insert into concelho (conc_id, conc_nome) values(1416,"Santarém");
insert into concelho (conc_id, conc_nome) values(1417,"Sardoal");
insert into concelho (conc_id, conc_nome) values(1418,"Tomar");
insert into concelho (conc_id, conc_nome) values(1419,"Torres Novas");
insert into concelho (conc_id, conc_nome) values(1420,"Vila Nova da Barquinha");
insert into concelho (conc_id, conc_nome) values(1421,"Ourém");
insert into concelho (conc_id, conc_nome) values(1401,"Abrantes");
insert into concelho (conc_id, conc_nome) values(1402,"Alcanena");
insert into concelho (conc_id, conc_nome) values(1403,"Almeirim");
insert into concelho (conc_id, conc_nome) values(1404,"Alpiarça");
insert into concelho (conc_id, conc_nome) values(1405,"Benavente");*/
insert into concelho (conc_id, conc_nome) values(1506,"Moita");
insert into concelho (conc_id, conc_nome) values(1507,"Montijo");
insert into concelho (conc_id, conc_nome) values(1508,"Palmela");
insert into concelho (conc_id, conc_nome) values(1509,"Santiago do Cacém");
insert into concelho (conc_id, conc_nome) values(1510,"Seixal");
insert into concelho (conc_id, conc_nome) values(1511,"Sesimbra");
insert into concelho (conc_id, conc_nome) values(1512,"Setúbal");
insert into concelho (conc_id, conc_nome) values(1513,"Sines");
insert into concelho (conc_id, conc_nome) values(1501,"Alcácer do Sal");
insert into concelho (conc_id, conc_nome) values(1502,"Alcochete");
insert into concelho (conc_id, conc_nome) values(1503,"Almada");
insert into concelho (conc_id, conc_nome) values(1504,"Barreiro");
insert into concelho (conc_id, conc_nome) values(1505,"Grândola");
/*insert into concelho (conc_id, conc_nome) values(1606,"Ponte da Barca");
insert into concelho (conc_id, conc_nome) values(1607,"Ponte de Lima");
insert into concelho (conc_id, conc_nome) values(1608,"Valença");
insert into concelho (conc_id, conc_nome) values(1609,"Viana do Castelo");
insert into concelho (conc_id, conc_nome) values(1610,"Vila Nova de Cerveira");
insert into concelho (conc_id, conc_nome) values(1601,"Arcos de Valdevez");
insert into concelho (conc_id, conc_nome) values(1602,"Caminha");
insert into concelho (conc_id, conc_nome) values(1603,"Melgaço");
insert into concelho (conc_id, conc_nome) values(1604,"Monção");
insert into concelho (conc_id, conc_nome) values(1605,"Paredes de Coura");
insert into concelho (conc_id, conc_nome) values(1705,"Mondim de Basto");
insert into concelho (conc_id, conc_nome) values(1706,"Montalegre");
insert into concelho (conc_id, conc_nome) values(1707,"Murça");
insert into concelho (conc_id, conc_nome) values(1708,"Peso da Régua");
insert into concelho (conc_id, conc_nome) values(1709,"Ribeira de Pena");
insert into concelho (conc_id, conc_nome) values(1710,"Sabrosa");
insert into concelho (conc_id, conc_nome) values(1711,"Santa Marta de Penaguião");
insert into concelho (conc_id, conc_nome) values(1712,"Valpaços");
insert into concelho (conc_id, conc_nome) values(1713,"Vila Pouca de Aguiar");
insert into concelho (conc_id, conc_nome) values(1714,"Vila Real");
insert into concelho (conc_id, conc_nome) values(1701,"Alijó");
insert into concelho (conc_id, conc_nome) values(1702,"Boticas");
insert into concelho (conc_id, conc_nome) values(1703,"Chaves");
insert into concelho (conc_id, conc_nome) values(1704,"Mesão Frio");
insert into concelho (conc_id, conc_nome) values(1805,"Lamego");
insert into concelho (conc_id, conc_nome) values(1806,"Mangualde");
insert into concelho (conc_id, conc_nome) values(1807,"Moimenta da Beira");
insert into concelho (conc_id, conc_nome) values(1808,"Mortágua");
insert into concelho (conc_id, conc_nome) values(1809,"Nelas");
insert into concelho (conc_id, conc_nome) values(1810,"Oliveira de Frades");
insert into concelho (conc_id, conc_nome) values(1811,"Penalva do Castelo");
insert into concelho (conc_id, conc_nome) values(1812,"Penedono");
insert into concelho (conc_id, conc_nome) values(1813,"Resende");
insert into concelho (conc_id, conc_nome) values(1814,"Santa Comba Dão");
insert into concelho (conc_id, conc_nome) values(1815,"São João da Pesqueira");
insert into concelho (conc_id, conc_nome) values(1816,"São Pedro do Sul");
insert into concelho (conc_id, conc_nome) values(1817,"Sátão");
insert into concelho (conc_id, conc_nome) values(1818,"Sernancelhe");
insert into concelho (conc_id, conc_nome) values(1819,"Tabuaço");
insert into concelho (conc_id, conc_nome) values(1820,"Tarouca");
insert into concelho (conc_id, conc_nome) values(1821,"Tondela");
insert into concelho (conc_id, conc_nome) values(1822,"Vila Nova de Paiva");
insert into concelho (conc_id, conc_nome) values(1823,"Viseu");
insert into concelho (conc_id, conc_nome) values(1824,"Vouzela");
insert into concelho (conc_id, conc_nome) values(1801,"Armamar");
insert into concelho (conc_id, conc_nome) values(1802,"Carregal do Sal");
insert into concelho (conc_id, conc_nome) values(1803,"Castro Daire");
insert into concelho (conc_id, conc_nome) values(1804,"Cinfães");
insert into concelho (conc_id, conc_nome) values(3105,"Ponta do Sol");
insert into concelho (conc_id, conc_nome) values(3106,"Porto Moniz");
insert into concelho (conc_id, conc_nome) values(3107,"Ribeira Brava");
insert into concelho (conc_id, conc_nome) values(3108,"Santa Cruz");
insert into concelho (conc_id, conc_nome) values(3109,"Santana");
insert into concelho (conc_id, conc_nome) values(3110,"São Vicente");
insert into concelho (conc_id, conc_nome) values(3101,"Calheta (Madeira)");
insert into concelho (conc_id, conc_nome) values(3102,"Câmara de Lobos");
insert into concelho (conc_id, conc_nome) values(3103,"Funchal");
insert into concelho (conc_id, conc_nome) values(3104,"Machico");
insert into concelho (conc_id, conc_nome) values(3201,"Porto Santo");
insert into concelho (conc_id, conc_nome) values(4101,"Vila do Porto");
insert into concelho (conc_id, conc_nome) values(4205,"Ribeira Grande");
insert into concelho (conc_id, conc_nome) values(4206,"Vila Franca do Campo");
insert into concelho (conc_id, conc_nome) values(4201,"Lagoa (São Miguel)");
insert into concelho (conc_id, conc_nome) values(4202,"Nordeste");
insert into concelho (conc_id, conc_nome) values(4203,"Ponta Delgada");
insert into concelho (conc_id, conc_nome) values(4204,"Povoação");
insert into concelho (conc_id, conc_nome) values(4301,"Angra do Heroísmo");
insert into concelho (conc_id, conc_nome) values(4302,"Praia da Vitória");
insert into concelho (conc_id, conc_nome) values(4401,"Santa Cruz da Graciosa");
insert into concelho (conc_id, conc_nome) values(4501,"Calheta (São Jorge)");
insert into concelho (conc_id, conc_nome) values(4502,"Velas");
insert into concelho (conc_id, conc_nome) values(4601,"Lajes do Pico");
insert into concelho (conc_id, conc_nome) values(4602,"Madalena");
insert into concelho (conc_id, conc_nome) values(4603,"São Roque do Pico");
insert into concelho (conc_id, conc_nome) values(4701,"Horta");
insert into concelho (conc_id, conc_nome) values(4801,"Lajes das Flores");
insert into concelho (conc_id, conc_nome) values(4802,"Santa Cruz das Flores");
insert into concelho (conc_id, conc_nome) values(4901,"Corvo");

